### ISSUE TITLE
Välja fraktsätt (Chrome)

### ISSUE THREAD

**Issue by jontesamuelsson** [evalentgroup/Magento-2-Ecster-Pay#1]
Det händer inget när man valt fraktalternativ i vänsterspalten. Det står bara ”Du måste välja ett fraktsätt för att gå vidare”. Detta händer bara i Chrome på pc och mac. Funkar som det ska i Edge på pc och Safari i macen. En ”workaround” verkar vara att välja att handla som ’företag’, då hoppar det fram. Sen går det välja tillbaka till ’privatperson’ så funkar det också. Så nånstans där kanske felet är…

**Comment by TobiasCodeNull** [comment]
Hej @jontesamuelsson 

Vi hanterar detta ärende i en separat mailtråd som du vet men jag håller ärendet öppet fram tills att vi vet mer om hur vi gör.

För info så gäller detta ett problem med Amastys Store Pickup modul som låter slutkunden att välja en butik att hämta produkterna. Ecster är inte anpassad för denna modul i nuläget.

**Comment by TobiasCodeNull** [comment]
Stänger ärendet då inga fler buggrapporter kommit in efter tillägg av Amasty Store Pickup kompatibilitet.
