### ISSUE TITLE
Multiple address lines not saved correctly in Magento

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#13]
Stumbled over an issue when a Customer enters two address lines. These are merged into one address line in Magento instead of two and also in the wrong order...

Example checkout (test customer):
![image](https://user-images.githubusercontent.com/25124716/91639652-6605eb00-ea18-11ea-8a43-ab379106043e.png)

In Magento:
![image](https://user-images.githubusercontent.com/25124716/91639685-9b123d80-ea18-11ea-8e8a-f35d67ae342a.png)

and:
![image](https://user-images.githubusercontent.com/25124716/91639701-bed58380-ea18-11ea-8f10-612a40f2b604.png)

**Comment by bve-9384** [comment]
The following fix solves this problem for us:
src/Model/Checkout.php

Replace
`"street" => $_billingAddress["line1"] . (isset($_billingAddress["line2"]) ? " " . $_billingAddress["line2"] : ""),`
with 
`"street" => (isset($_billingAddress["line2"]) ? $_billingAddress["line2"] . "\n" : "") . $_billingAddress["line1"],`

Replace
`"street" => $_shippingAddress["line1"] . (isset($_shippingAddress["line2"]) ? " " . $_shippingAddress["line2"] : ""),`
with
`"street" => (isset($_shippingAddress["line2"]) ? $_shippingAddress["line2"] . "\n" : "") . $_shippingAddress["line1"],`

Replace
`"street" => $_address["line1"] . (isset($_address["line2"]) ? " " . $_address["line2"] : ""),`
with
`"street" => (isset($_address["line2"]) ? $_address["line2"] . "\n" : "") . $_address["line1"],`

**Comment by TobiasLufinity** [comment]
Thanks for the bug report and the suggested fix. I've added your fix and will be in the next release.
