### ISSUE TITLE
Cart discount description always in English in the Ecster payment confirmation email

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#15]
Cart discounts are always called "Discount" in the Ecster payment confirmation email, even if the language is not set to English.

The following change fixed this issue for us, in Model/Api/Ecster.php, from:

`            $items[] = $this->createDummyItem($this->getAddress()->getDiscountAmount(), "Discount", "Discount");`

to:

`            $items[] = $this->createDummyItem($this->getAddress()->getDiscountAmount(), __('Discount'), "Discount");`

Found similar constructs in:
Observer/SalesOrderInvoiceRegister.php
Observer/SalesOrderPaymentRefund.php

Testing with plugin version 1.0.7, magento ce 2.3.6

**Comment by TobiasLufinity** [comment]
This was added in the latest release of 1.0.8
