### ISSUE TITLE
Create order from OEN when redirect fails

### ISSUE THREAD

**Issue by alexander-js** [evalentgroup/Magento-2-Ecster-Pay#21]
If a user does not get redirected to `/ecster-reference/<reference>` upon successful payment, an order never gets created - unless payment was [performed via Swish](https://github.com/evalentgroup/Magento-2-Ecster-Pay/blob/master/src/Model/SalesOrderStatusUpdate.php#L265-L273).

There are other cases where we would also like to construct an order from an OEN message. For example:
- The customer loses connection as the payment is being processed.
- The customer closes the tab/navigates away as the payment is being processed.

When this happens, the customer might receive a confirmation email from Ecster, but a Magento order will actually never be created because they never got redirected to `/ecster-reference/<reference>`. Could we handle these cases similarly to Swish by automatically creating orders from the OEN data instead of letting it fail? Thanks for your time.

**Comment by TobiasLufinity** [comment]
The creation from OEN does not actually depend on the payment method rather the payment status as you can see in src/Model/SalesOrderStatusUpdate.php:265.
So if you like all orders to be created through OEN after the delay then you can remove the FULLY_DELIVERED and FULL_DEBIT requirement using a preference or a plugin in di.xml.

Although, the email from Ecster is sent after a payment is debited which will result in the OEN event FULLY_DELIVERED being triggered which will create the order in Magento. So the example with the Ecster confirmation being sent to a customer without it being debited shouldn't be possible.
