### ISSUE TITLE
guzzlehttp/guzzle - Konflikt

### ISSUE THREAD

**Issue by jontesamuelsson** [evalentgroup/Magento-2-Ecster-Pay#26]
Problem vid installation av modulen i Magento Open Source 2.4.5-p1.
Andra delar av installationen verkar kräva högre version av guzzlehttp/guzzle.

`Problem 1
    - evalent/module-ecsterpay[1.0.0-beta.1, ..., 1.2.2] require guzzlehttp/guzzle ~6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.8] but the package is fixed to 7.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires evalent/module-ecsterpay ^1.0 -> satisfiable by evalent/module-ecsterpay[1.0.0-beta.1, ..., 1.2.2].`

**Comment by jontesamuelsson** [comment]
- magento/framework[103.0.5, ..., 103.0.5-p1] require guzzlehttp/guzzle ^7.4.2 -> satisfiable by guzzlehttp/guzzle[7.4.2, ..., 7.5.0].

**Comment by TobiasLufinity** [comment]
Dependency uppdaterad så det går bra att installera på Magento 2.4.5-p1
