### ISSUE TITLE
Inläsning av fraktsätt

### ISSUE THREAD

**Issue by jontesamuelsson** [evalentgroup/Magento-2-Ecster-Pay#28]
Problem när kassan ska läsa in fraktsätt i 2.4.5-p1.

[ERROR] Failed to load the "Evalent_EcsterPay/shipping" template requested by "checkout.steps.shipping-step.shippingAddress".

Den läser inte in fraktsätten i vänsterspalten och säger att man måste välja fraktsätt för att gå vidare.

Har avaktiverat alla fraktsätt utom två som är standard i Magento; 'Flat Rate' och 'Free shipping'. Det hjälpte inte dessvärre. Tänkte det var min Amasty Store Pickup som ställde till det, men den är avaktiverad nu.

**Comment by TobiasLufinity** [comment]
Problemet var självstängande element i shipping template. Dessa är åtgärda nu och jag har fått genom köp med Magento standard shipping rate.
Kolla så det fortfarande funkar med Store Pickup också då jag inte har tillgång till denna modulen,

**Comment by jontesamuelsson** [comment]
Hej Tobias

Nu funkade den. Testade även med amasty-modulen (Hämta i butik), verkar också funka.
DOCK tänker jag mig att byta till In-Store Pickup-modulen som i och med version 2.4 är ingår i magentoinstallationen.
Då kan jag skrota amasty-modulen som för vår shop är onödigt avancerad.
Testade att aktivera denna inbyggda In-Store Pickup, den verkar inte lira helt hundra dock. Kan välja fraktsättet, men jag kan inte välja utlämningsställe/butik

Bifogar även en bild på kassan/fraktsätten, jag tycker det sakas ”radio buttons”. Kan fortfarande välja, men det känns inte användarvänligt.

Vill du jag lägger in nya githud-ärenden på detta?





Jonatan Samuelsson
Motorsport i Vimmerby AB
0492-134 60 | www.motorsport.se <http://www.motorsport.se/>

**Comment by TobiasLufinity** [comment]
Hej Jonatan,

Ja,

gör gärna det men detta kommer jag tyvärr inte kunna fixa förens vi har ett avtal med Ecster.
Går det bra att använda Amasty modulen tills det sker?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jontesamuelsson** [comment]
Förstår läget :-)
Perfekt, då lägger jag in det på GitHub.
Jag kan köra amasty-modulen tills vidare.
Tack för snabb hjälp.

//Jonatan
Jonatan Samuelsson
Motorsport i Vimmerby AB
0492-134 60 | www.motorsport.se
