### ISSUE TITLE
Partial refund

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#3]
I am quite sure that partial refund used to be enabled before but somehow it is no longer possible in version 1.0.0. This makes it quite tricky to handle returns when not all order items are returned.

It seems that adding the following to Model/Gateway.php does the trick:

```
    public function canRefundPartialPerInvoice()
    {
        return true;
    }
```

**Comment by TobiasCodeNull** [comment]
Issue fixed and released in 1.0.1
