### ISSUE TITLE
Invoice after successful Swish payment

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#5]
I understand that Invoices in Magento are the record of payment received. If there is no invoice, Magento will think that you haven’t been paid for the order. We rely on invoice objects for integration with bookkeeping, reports etc.

Ecster Swish payments however do not result in Magento invoices. It is also not possible to create Magento invoices for Swish orders manually. I would expect that a Magento invoice always is created automatically with every successful Swish payment, independently of the "Auto Create Invoice" setting in the Ecster options.

No invoices also means that one cannot create credit memos for Swish orders which complicates returns.

**Comment by TobiasCodeNull** [comment]
I've modified the functions so an Invoice is created when payment is done with Swish. A Creditmemo can be made but will be refunded offline as Ecster does not support synchronous transaction flow for Swish payment. 
The order can be handled to full extent i Magento but a real credit has to be made in Ecster.
