### ISSUE TITLE
Delayed OEN messages sometimes cause incorrect order cancellation

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#6]
We can see that quite often initial OEN messages cannot be processed because the ecster key is not yet saved against the order. Generating the following messages in system.log:
```
main.INFO: OEN error: Ecster OPN: Could not find order by (removed) ecster reference number.. Retrying once in 10 sec
main.INFO: Ecster OPN: Could not find order by (removed) ecster reference number. 
```
This does not seem to be a problem by itself but becomes a problem two hours later when Ecster resends the messages that could not be processed earlier, especially for "PENDING_PAYMENT" notifications. We have had several cases in one day where the order state changes from PROCESSING back to PENDING_PAYMENT. By default Magento cancels PENDING_PAYMENT orders after 8 hours :-(

The solution seems to be quite straight forward (after reading this [Ecster doc](https://developer.ecster.se/appi/api/#order-event-notification-oen)): The OEN handler should not trust the order status in the OEN message but instead fetch the current order status by calling the Ecster API.

**Comment by TobiasCodeNull** [comment]
We've managed to get the OEN order status update to work better. So when a order is pending_payment in Ecster you can choose which status this correspondence to in Magento so the order won't be cancelled.

You can choose this in version 1.0.2 in configuration under Ecster in Magento

**Comment by bve-9384** [comment]
@TobiasCodeNull not fetching the current status from Ecster when processing the OEN can still result in incorrect order transitions. 

Thinking of the following info from the Ecster docs:
_NOTE As the name indicates, Async OEN is an asynchronous notification. An OEN can be sent within seconds but can also be delayed for minutes, thus you should NOT build your application relying on an OEN being sent within a certain amount of time.
Ecster recommends that the merchant makes a get order request with the orderId to get all the updated order information from the response when an async OEN is received_

We see many 2 hour old OEN messages which today incorrectly try to revert the order state and status in Magento.

I also noted that state and status are being mixed up in SalesOrderStatusUpdate::process(). State can only be new, pending_payment, processing, complete, closed, canceled, holded or payment_review while statu**s** is more flexible.
