### ISSUE TITLE
HTTP 500 error handling

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#7]
Server errors from the Ecster API result in "JSON Error" messages in admin instead of the Ecster message. 
The following changes to Helper/Data.php fix this:
- "use GuzzleHttp\Exception\BadResponseException" instead of "use GuzzleHttp\Exception\ClientException"
- "catch (BadResponseException $ex)" instead of "catch (ClientException $ex)"

Trying to create an invoice for a Swish order triggers a server error for instance, with json in the response body.

**Comment by TobiasCodeNull** [comment]
I made the requested changes so the JSON body exceptions is displayed in admin.
