### ISSUE TITLE
Magento order in invalid state after failed Ecster DEBIT

### ISSUE THREAD

**Issue by bve-9384** [evalentgroup/Magento-2-Ecster-Pay#8]
The Magento order gets in a semi-invoiced state when the Ecster DEBIT API call fails. Not allowing a second try (the Invoice button in Magento is no longer visible).

This seems to be caused by the SalesOrderInvoiceRegister observer saving the order before the DEBIT API call. Moving the following statement to just before the invoice save seems to solve this problem (Observer/SalesOrderInvoiceRegister.php):
`$order->setEcsterExtraInvoiceRemainFee($order->getEcsterExtraInvoiceRemainFee() + $invoice->getEcsterExtraFee())->save()`

**Comment by TobiasCodeNull** [comment]
Issue fixed and will be released in the 1.0.2 release
